alter table public.listings
add column if not exists delivery_method text default 'collection_only',
add column if not exists delivery_provider text,
add column if not exists delivery_available boolean default false,
add column if not exists caterbids_delivery_available boolean default false,
add column if not exists collection_full_address text,
add column if not exists collection_postcode text,
add column if not exists collection_city text,
add column if not exists seller_contact_name text,
add column if not exists seller_phone text,
add column if not exists pallet_size text,
add column if not exists pallet_ready boolean default false,
add column if not exists pallet_weight_kg numeric,
add column if not exists pallet_length_cm numeric,
add column if not exists pallet_width_cm numeric,
add column if not exists pallet_height_cm numeric,
add column if not exists pallet_count integer default 1,
add column if not exists tail_lift_required boolean default false,
add column if not exists forklift_available boolean default false,
add column if not exists commercial_premises boolean default true,
add column if not exists shrink_wrapped_confirmed boolean default false,
add column if not exists pallet_preparation_confirmed boolean default false,
add column if not exists preferred_collection_date date,
add column if not exists insurance_value numeric,
add column if not exists access_restrictions text,
add column if not exists delivery_notes text,
add column if not exists delivery_details_confirmed boolean default false;

alter table public.orders
add column if not exists delivery_method text,
add column if not exists delivery_provider text,
add column if not exists delivery_name text,
add column if not exists delivery_price numeric default 0,
add column if not exists delivery_status text default 'not_required',
add column if not exists delivery_booking_required boolean default false,
add column if not exists buyer_delivery_full_address text,
add column if not exists buyer_delivery_postcode text,
add column if not exists buyer_phone text,
add column if not exists buyer_access_restrictions text,
add column if not exists collection_full_address text,
add column if not exists collection_postcode text,
add column if not exists collection_city text,
add column if not exists seller_contact_name text,
add column if not exists seller_phone text,
add column if not exists pallet_size text,
add column if not exists pallet_ready boolean default false,
add column if not exists pallet_weight_kg numeric,
add column if not exists pallet_length_cm numeric,
add column if not exists pallet_width_cm numeric,
add column if not exists pallet_height_cm numeric,
add column if not exists pallet_count integer default 1,
add column if not exists tail_lift_required boolean default false,
add column if not exists forklift_available boolean default false,
add column if not exists commercial_premises boolean default true,
add column if not exists shrink_wrapped_confirmed boolean default false,
add column if not exists pallet_preparation_confirmed boolean default false,
add column if not exists preferred_collection_date date,
add column if not exists insurance_value numeric,
add column if not exists access_restrictions text,
add column if not exists delivery_notes text,
add column if not exists delivery_booking_reference text,
add column if not exists delivery_tracking_number text,
add column if not exists delivery_label_url text;
